<?php /*
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */ ?>

<div class="form-default">
    <?php
    /** @var \User\Form\Forgot\ChangePasswordForm $form */
    $form = $this->form;

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('new_password')) . '<br />';
    echo $this->formRow($form->get('confirm_new_password')) . '<br />';
    echo $this->formRow($form->get('submit')->setLabel('Save'));
    echo $this->formRow($form->get('csrf'));
    echo $this->form()->closeTag($form);
    ?>
</div>