<div class="form-default">
    <?php
    /** @var \User\Form\Forgot\RequestForm $form */
    $form = $this->form;

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('email')->setLabel('Email Adresse eingeben'));
    echo $this->formRow($form->get('submit')->setLabel('Neues Passwort anfordern'));
    echo $this->formRow($form->get('csrf'));
    echo $this->form()->closeTag($form);
    ?>
</div>

