  
<?php foreach ($form as $element) : ?>

    <div class="form-group<?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $this->translate($element->getLabel()) ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                    ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-success');
        }
        if ($element instanceof Zend\Form\Element\Captcha) {
            echo $this->formCaptcha($element);
        } else {

            if ($element instanceof Zend\Form\Element\Checkbox) {
                $element->setAttribute('class', ' ');
                echo $this->formElement($element);
            } else {
                echo $this->formElement($element);
            }
        }
        if ($this->formElementErrors($element)) :
            ?>
            <?php
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<p class="help-block">')
                    ->setMessageSeparatorString('</p><p class="help-block">')
                    ->setMessageCloseString('</p>')
                    ->render($element);
            ?>
        <?php endif; ?>
    </div>
    <?php
endforeach;
if ($this->redirect):
    ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?php echo $this->form()->closeTag() ?>