<div class="form-default">
    <?php
    $form = $this->createUserForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin/create'));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
   <div class="page-header">
        <h1>Edit user</h1>
    </div>
    <div class="form-group form-default"> 
        <?php include '_form.phtml'; ?>
    </div>
</div>
