<?php
/*
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */

$form = $this->createUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/create'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<div class="form-default">
    <div class="page-header">
        <h1>Neuer Benutzer</h1>
    </div>
    <div class="form-group form-default"> 
        <?php include '_form.phtml'; ?>
    </div>
</div>
