<div class="form-default">
    <?php
    $form = $this->editUserForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin/edit', array('userId' => $this->userId)));
    $form->setAttribute('method', 'post');
    ?>
    <div class="page-header">
        <h1>Edit user</h1>
    </div>
    <div class="form-group form-default"> 
        <?php include '_form.phtml'; ?>
    </div>
    <a href="<?php echo $this->url('admin/remove', array('userId' => $this->userId)); ?>"
       onclick="return confirm('<?php echo $this->translate('Really delete user?') ?>')">
           <?php echo $this->translate('Delete') ?>
    </a>
</div>
