
<?php
$form = $this->editUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/edit', array('userId' => $this->userId)));
$form->setAttribute('method', 'post');
?>
<div class="form-default">
    <div class="page-header">
        <h1>Edit user</h1>
    </div>
    <div class="form-group"> 
        <?php include '_form.phtml'; ?>
    </div>

    <a href="<?php echo $this->url('admin/remove', array('userId' => $this->userId)) ?>" class="btn btn-delete" onclick="return confirm('<?php echo $this->translate('Sind Sie sicher ?') ?>')">
        <?php echo $this->translate('Löschen') ?>
    </a>
    <br>
    <br>
    <a href="<?php echo $this->url('admin/list') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><span class="glyphicon glyphicon-cog"></span><?php echo $this->translate(' Verwaltung'); ?></a>
</div>
