<?php
/*
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */

$getters = array();
foreach ($this->userlistElements as $element) {
    $parts = explode('_', $element);
    array_walk($parts, function (&$val) {
        $val = ucfirst($val);
    });
    $getters[$element] = 'get' . implode('', $parts);
}
?>

<div class="page-header text-center">
    <h1><?php echo $this->translate('Benutzerverwaltung'); ?>
    </h1>
</div>

<div class="navbar filter-bar">
    <div class="navbar-inner">
        <div class="text-center">
            <a href="<?php echo $this->url('admin/create') ?>" class="btn btn-lg btn-info">
                <?php echo $this->translate('Neuen User erstellen') ?>
            </a>
        </div>
    </div>
</div>

<table class="table panel-body">
    <thead>
        <tr>
            <?php foreach ($this->userlistElements as $name => $element): ?>
                <th><?php echo $this->escapeHtml($name ? : $element); ?></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <?php foreach ($this->userlistElements as $element): ?>
                <td class="cell cell-<?php echo $this->escapeHtml($element) ?>">
                    <?php $parts = explode('_', $element); ?>
                    <?php echo call_user_func(array($user, $getters[$element])); ?>
                </td>
            <?php endforeach; ?>
            <td class="cell cell-ctrls">
                <a href="<?php echo $this->url('admin/edit', array('userId' => $user->getId())); ?>">
                    <?php echo $this->translate('Editieren') ?>
                </a>
                |
                <a href="<?php echo $this->url('admin/remove', array('userId' => $user->getId())); ?>"
                   onclick="return confirm('<?php echo $this->translate('Sind Sie sicher ?') ?>')">
                       <?php echo $this->translate('Löschen') ?>
                </a>
            </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr class="text-center">
                <td colspan="<?php echo count($this->userlistElements) + 1; ?>">
                    <?php echo $this->paginationControl($this->users, 'Sliding', 'user/admin/pagination_userlist.phtml'); ?>
                </td>
            </tr>
        </tfoot>
</table>
