<?php
/* 
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */
$form = $this->form;

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email')) . '<br />';
echo $this->formRow($form->get('cred')) . '<br />';
echo $this->formRow($form->get('submit')->setLabel($this->translate('Account aktivieren')));
echo $this->formRow($form->get('csrf'));
echo $this->form()->closeTag($form);