<?php /*
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */ ?>

<div class="form-default">
    <?php echo $this->form()->closeTag(); ?>
    <div class="page-header">
        <h1><?php echo sprintf($this->translate('Passwort ändern'), $this->zfcUserDisplayName()); ?></h1>
    </div>
    <?php if ($status === true) : ?>
        <div class="alert alert-success"><?php echo $this->translate('Password erfolgreich geändert.'); ?></div>
    <?php elseif ($status === false) : ?>
        <div class="alert alert-danger"><?php echo $this->translate('Ihr Passwort konnte nicht zurückgesetzt werden. Bitte Versuchen Sie es erneut.'); ?></div>
    <?php endif; ?>
    <?php
    $form = $this->changePasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');

    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());

    echo $this->form()->openTag($form);
    ?>
    <a href="<?php echo $this->url('zfcuser') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><span class="glyphicon glyphicon-home"></span><?php echo $this->translate(' Mein Profil'); ?></a>
    <?php foreach ($form as $element) : ?>

        <div  class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
            <?php if ('submit' != $element->getAttribute('type')) { ?>
                <label class="control-label"><?php echo $element->getLabel() ?></label>
                <?php
                $element->setAttribute('class', 'form-control')
                        ->setAttribute('placeholder', $element->getLabel());
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            if ($element instanceof Zend\Form\Element\Captcha) {
                echo $this->formCaptcha($element);
            } else {
                echo $this->formElement($element);
            }
            if ($this->formElementErrors($element)) :
                ?>
                <?php
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
                ?>
            <?php endif; ?>
        </div>

    <?php endforeach; ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    <?php echo $this->form()->closeTag() ?>
</div>