<?php echo $this->form()->closeTag(); ?>
    <div class="page-header">
        <h1><?php echo sprintf($this->translate('Change Adress for %s'), $this->zfcUserDisplayName()); ?></h1>
    </div>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Ihre Adresse wurde erfolreich geändert.');?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-danger"><?php echo $this->translate('Ihr Adresse konnte nicht geändert werden. Bitte Versuchen Sie es erneut.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changeAdressForm;
$form->prepare();
$form->setAttribute('action', $this->url('change-adress'));
$form->setAttribute('method', 'post');
$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);
?>

<?php foreach ($form as $element) : ?>

    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
        if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-success');
        }
        if ($element instanceof Zend\Form\Element\Captcha) {
            echo $this->formCaptcha($element);
        } else {
            echo $this->formElement($element);
        }
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>

<?php
endforeach;?>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?php echo $this->form()->closeTag() ?>