
<div class="form-default">
    <?php echo $this->form()->closeTag(); ?>
    <div class="page-header">
        <h1><?php echo sprintf($this->translate('Daten ändern'), $this->zfcUserDisplayName()); ?></h1>
    </div>
    <?php if ($status === true) : ?>
        <div class="alert alert-success"><?php echo $this->translate('Ihre Eingabe wurde erfolreich geändert.'); ?></div>
    <?php elseif ($status === false) : ?>
        <div class="alert alert-danger"><?php echo $this->translate('Ihre Eingabe konnte nicht geändert werden. Bitte Versuchen Sie es erneut.'); ?></div>
    <?php endif; ?>
    <?php
    $form = $this->changeAdressForm;
    $data = $this->AccountDisplay();
    $form->prepare();
    $form->setAttribute('action', $this->url('change-adress'));
    $form->setAttribute('method', 'post');
    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());

    echo $this->form()->openTag($form);
    ?>
 <a href="<?php echo $this->url('zfcuser') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><span class="glyphicon glyphicon-home"></span><?php echo $this->translate(' Mein Profil'); ?></a>

    <?php foreach ($form as $element) : ?>

        <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
            <?php if ('submit' != $element->getAttribute('type')) { ?>
                <label class="control-label"><?php echo $element->getLabel() ?></label>
                <?php
                $element->setAttribute('class', 'form-control');
                /*if the name matches wie give them infos about the valaûe which is set right-now*/
                if ($element->getName() == 'newStreet') {
                    $element->setAttribute('value', $data['street']);
                } elseif ($element->getName() == 'newPlz') {
                    $element->setAttribute('value', $data['plz']);
                } elseif ($element->getName() == 'newVillage') {
                    $element->setAttribute('value', $data['village']);
                } elseif ($element->getName() == 'newDisplayname') {
                    $element->setAttribute('value', $data['displayname']);
                } elseif ($element->getName() == 'newUsername') {
                    $element->setAttribute('value', $data['username']);
                } elseif ($element->getName() == 'newPhone') {
                    $element->setAttribute('value', $data['phone']);
                }
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            if ($element instanceof Zend\Form\Element\Captcha) {
                echo $this->formCaptcha($element);
            } else {
                echo $this->formElement($element);
            }
            if ($this->formElementErrors($element)) :
                ?>
                <?php
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
                ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <br>
 
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
</div>
<?php echo $this->form()->closeTag() ?>