
<?php if (isset($name)) { ?>
Dear <?=$name?><br />
<br />
<?php } ?>
Sie haben ein neues Passwort angefordert, um ein neues zu erstellen klicken Sie auf den untenstehenden Link:<br />
<br /><br />
<?php  
echo $_SERVER['SERVER_NAME'];
?>
<br />
<?php  
echo 'https://theothersite.ch'.$this->url();
?>
<br>
<a href="<?=$this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?>"><?=$this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?></a><br />
<br />
Wenn Sie diese Email Irrtuemlicherweise bekommen haben, koennen Sie diese ignorieren.

