
<?php if (isset($name)) { ?>
    Dear <?= $name ?><br />
    <br />
<?php } ?>
Sie haben ein neues Passwort angefordert, um ein neues zu erstellen klicken Sie auf den untenstehenden Link:<br />
<br /><br />
<?php

function curPageURL() {
    $pageURL = 'http';
    if ($_SERVER["HTTPS"] == "on") {
        $pageURL .= "s";
    }
    $pageURL .= "://";
    if ($_SERVER["SERVER_PORT"] != "80") {
        $pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"] . $_SERVER["REQUEST_URI"];
    } else {
        $pageURL .= $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
    }
    return $pageURL;
}
?>
<br />
<?php
echo curPageURL();
?>
<br>
<a href="<?= $this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true]) ?>"><?= $this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true]) ?></a><br />
<br />
Wenn Sie diese Email Irrtuemlicherweise bekommen haben, koennen Sie diese ignorieren.

