
<?php if (isset($name)) { ?>
Dear <?=$name?><br />
<br />
<?php } ?>
Sie haben ein neues Passwort angefordert, um ein neues zu erstellen klicken Sie auf den untenstehenden Link:<br />
<br />
<a href="<?=$this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?>"><?=$this->url('user/forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?></a><br />
<br />
Wenn Sie diese Email Irrtümlicherweise bekommen haben, können Sie diese ignorieren.

