<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?> 


        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Title App"/>&nbsp;TitleText</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($this->container as $page) { ?>
                            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                            <?php // when using partials we need to manually check for ACL conditions ?>
                            <?php
                            if (!$page->isVisible() || !$this->navigation()->accept($page)) {
                                continue;
                            }
                            ?>
    <?php $hasChildren = $page->hasPages(); ?>
                                    <?php if (!$hasChildren) { ?>
                                <li>
                                    <a href="<?php echo $page->getHref() ?>">
                                <?php echo $this->translate($page->getLabel()) ?>
                                    </a>
                                </li>
    <?php } else { ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate($page->getLabel()) ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($page->getPages() as $child) { ?>
                                            <?php // when using partials we need to manually check for ACL conditions  ?>
                                            <?php
                                            if (!$child->isVisible() || !$this->navigation()->accept($child)) {
                                                continue;
                                            }
                                            ?>
                                            <li>
                                                <a href="<?php echo $child->getHref() ?>">
            <?php echo $this->translate($child->getLabel()) ?>
                                                </a>
                                            </li>
                                <?php } ?>
                                    </ul>
                                </li>
    <?php } ?>
<?php } ?>
                    </ul>
                </div>
            </div>
        </nav>






        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by TeamHangLoose <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
