<?php
$title = $this->translate('Profilbild ändern');
$title = $this->escapeHtml($title);
$this->headTitle($title);
$form->prepare();
?>
<div class="container form-default">
    <div class="page-header">
        <h2><?php echo $title; ?></h2>
    </div>
    <?php if ($user->getId() == $this->zfcUserIdentity()->getId()): ?>
        <div class="row">
            <div class="col-sm-6">
                <?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
            </div>

            <div class="col-sm-6">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formElement($form->get('image')) . $this->formElementErrors($form->get('image')); ?>
            </div>
        </div>


        <a href="<?php echo $this->url('zfcuser'); ?>" class="btn btn-info">
            <?php echo $this->translate('Zurück zu meinem Profil'); ?>
        </a>

    <?php endif; ?>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('image')) . $this->formElementErrors($form->get('image')); ?>
    <br/>
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->form()->closeTag($form); ?>
</div>
