<?php

$title = $this->translate('Profilbild ändern von ') . $user->getUserName();
$title = $this->escapeHtml($title);
$this->headTitle($title);
$form->prepare();
?>

<h2 class="page-header"><?php echo $title; ?></h2>
<?php if ($imageUploaded): ?>
    <div class="alert alert-success"><?php echo $this->translate("Bild erfolgreich geändert") ?></div>
<?php endif; ?>
<?php if ($user->getId() == $this->zfcUserIdentity()->getId()): ?>
    <a href="<?php echo $this->url('zfcuser'); ?>" class="btn btn-info">
        <?php echo $this->translate('Zurück zu meinem Profil'); ?>
    </a>
    <br/><br/>
<?php endif; ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('image')) . $this->formElementErrors($form->get('image')); ?>
<br/>
<?php echo $this->formElement($form->get('submit')); ?>
<?php echo $this->form()->closeTag($form); ?>
