<?php
/*
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author  abbts2015 B14.if4.1 G.3
 */
$title = $this->translate('Profilbild ändern');
$title = $this->escapeHtml($title);
$this->headTitle($title);
$form->prepare();
?>
<div class="container form-default text-center">
    <div class="page-header">
        <h1><?php echo $title; ?></h1>
    </div>
    <a href="<?php echo $this->url('zfcuser') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><span class="glyphicon glyphicon-home"></span><?php echo $this->translate(' Mein Profil'); ?></a>
    <br>
    <br>
    <?php if ($user->getId() == $this->zfcUserIdentity()->getId()): ?>
        <?php echo $this->form()->openTag($form); ?>
        <div class="text-center">
            <p><?php echo $this->htProfileImage($this->zfcUserIdentity()) ?></p>
            <br>
            <p><?php echo $this->formElement($form->get('image')) . $this->formElementErrors($form->get('image')); ?></p>
        </div>
    <?php endif; ?>
    <br>
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->form()->closeTag($form); ?>
</div>

