<?php
$data = $this->AccountDisplay();
?>


<div class="container"> 
    <div class="text-center page-header">
        <h1><?php echo $this->translate('Hallo'); ?>, <?php echo $this->zfcUserDisplayName() ?> !
        </h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="panel-body text-center">
                    <P><?php echo $this->htProfileImage($this->zfcUserIdentity()) ?></p>
                    <p><a class="btn btn-default" href="<?php echo $this->url('zfcuser/htimageupload') ?>"><?php echo $this->translate('Bild ändern'); ?></a></p>
                </div>
            </div>

            <div class="col-sm-8 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Persönliche Daten') ?></h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <label class="control-label col-xs-4" ><?php echo $this->translate('Vorname Nachname') ?></label>
                                <div class="col-xs-6">
                                    <input disabled="true" type="text" class="form-control" placeholder="<?php echo $data['username'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-4"><?php echo $this->translate('Benutzername') ?></label>
                                <div class="col-xs-6">
                                    <input disabled="true" type="text" class="form-control" placeholder="<?php echo $data['displayname'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-4"><?php echo $this->translate('Strasse') ?></label>
                                <div class="col-xs-6">
                                    <input disabled="true" type="text" class="form-control" placeholder="<?php echo $data['street'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-4"><?php echo $this->translate('Postleitzahl') ?></label>
                                <div class="col-xs-6">
                                    <input disabled="true" type="text" class="form-control" placeholder="<?php echo $data['plz'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-4"><?php echo $this->translate('Ort') ?></label>
                                <div class="col-xs-6">
                                    <input disabled="true" type="text" class="form-control" placeholder="<?php echo $data['village'] ?>">
                                </div>
                            </div>
                            <div class="form-group text-center">
                                <a class="btn btn-default" href="<?php echo $this->url('change-adress') ?>"><?php echo $this->translate('Daten Ändern'); ?></a> 
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-8 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Persönliche Daten') ?></h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal">

                            <div class="panel-body">
                                <form class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label col-xs-4"><?php echo $this->translate('Email') ?></label>
                                        <div class="col-xs-6">
                                            <input disabled="true" type="email" class="form-control" placeholder="<?php echo $data['email'] ?>">
                                        </div>
                                    </div>
                                    <div class="form-group text-center">
                                        <a class="btn btn-default" href="<?php echo $this->url('zfcuser/changeemail') ?>"><?php echo $this->translate('Daten Ändern'); ?></a> 
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-4"></label>
                                        <div class="col-xs-6">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-4"><?php echo $this->translate('Passwort') ?></label>
                                        <div class="col-xs-6">
                                            <input disabled="true" type="password" class="form-control" placeholder=<?php echo $this->translate(' ***** ') ?>>
                                        </div>
                                    </div>
                                    <div class="form-group text-center">
                                        <a class="btn btn-default" href="<?php echo $this->url('zfcuser/changepassword') ?>"><?php echo $this->translate('Daten Ändern'); ?></a> 
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
<div class="row">
    <div class="col-sm-4">
    </div>

    <div class="col-sm-8 ">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Weitere Daten') ?></h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-xs-4"><?php echo $this->translate('Email') ?></label>
                        <div class="col-xs-6">
                            <input disabled="true" type="email" class="form-control" id="inputPassword" placeholder="<?php echo $data['email'] ?>">
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
-->