
<div style="float:left; padding-right:16px;">
    <?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
</div>

<h3>
    <?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!
</h3>

<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<a href="<?php echo $this->url('change-adress') ?>">[<?php echo $this->translate('Change Adress'); ?>]</a>
<a href="<?php echo $this->url('zfcuser/changepassword') ?>">[<?php echo $this->translate('Change Password'); ?>]</a>
<?php
$data = $this->AccountDisplay();
echo ' <br>Name: ' . $data['displayname'] . '<br>' . $data['username'] . '<br>' . $data['email'] . '<br>' . $data['street'] . '<br>' . $data['plz'] . '<br>' . $data['village'];
?>
<hr><br>

<div style="clear:both;"></div>

<a href="<?php echo $this->url('zfcuser/htimageupload') ?>"><?php echo $this->translate('Upload image'); ?></a>



<!-- NEW FORM -->

<div class="container">    <div class="row">
        <div class ="page-header">
            <div class="col-md-6 text-center">
                <?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
            </div>
        </div>
    </div>



    <div class="col-md-6">
        <h1 class="">
            <?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?> !
        </h1>
    </div>


</div>
