

<!--
<div class="form-default">
    <div class="form-default">
        <h3>
<?php echo $this->translate('Hallo'); ?>, <?php echo $this->zfcUserDisplayName() ?>!
        </h3>
    </div>


    <div class="container-fluid"
         <div class="row">
            <div class="col-md-4">
<?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
            </div>
                          
        </div>
    </div>

-->

<div style="float:left; padding-right:16px;">
    <?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
</div>

<h3>
    <?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!
</h3>

<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>

<?php 
$data = $this->AccountDisplay(); 
echo ' <br>'.$data['displayname'].'<br>'.$data['username'].'<br>'.$data['email'].'<br>'.$data['street'].'<br>'.$data['plz'].'<br>'.$data['village'];
 ?>
<hr><br>

<div style="clear:both;"></div>

<a href="<?php echo $this->url('zfcuser/htimageupload') ?>"><?php echo $this->translate('Upload image'); ?></a>



<!-- NEW FORM -->

<div class="container">

    <div class="alert alert-success" role="alert"> Wilkommen <?php echo $this->zfcUserDisplayName() ?>
    </div>

    <div class="row page-header">
        <div class="col-md-12 text-center">
            <?php echo $this->htProfileImage($this->zfcUserIdentity()) ?>
        </div>
    </div>

    <div class="col-md-12">
        <h1 class="">
            <?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?> !
        </h1>
    </div>


</div>
