<div class="pageheadern text-center">
    <h2>Informationen</h2>
</div>
<div class="row-fluid">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Feststand') ?></h3>
            </div>
            <div class="row-fluid">
                <div class="col-md-4">
                    <div class="panel-body">blblbl
                        <img class="img-responsive" src="http://www.jroller.com/alexRuiz/resource/fest10.png">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel-body">
                        <p><?php echo sprintf($this->translate('Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt.')) ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
