<div class="container">
    <div class="page-header text-center">
        <h2>Informationen</h2>
    </div>
    <div class="panel-group" id="accordion">
        <div class="row">
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                Festwirtschaft</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse-in">
                        <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                            minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                            commodo consequat.</div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">

                <div id="collapse-img" class="panel-collapse collapse-in">
                    <div class="panel-body">
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li>
                                <li data-target="#myCarousel" data-slide-to="2"></li>
                                <li data-target="#myCarousel" data-slide-to="3"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                <div class="item active img-responsive">
                                    <img src="http://www.buuramart.ch/produkt_bratwurst.jpg" alt="Bratwurst">
                                </div>

                                <div class="item img-responsive">
                                    <img src="http://agroscope.files.wordpress.com/2013/02/festwirtschaft.jpg" alt="Salat">
                                </div>

                                <div class="item img-responsive">
                                    <img src="http://www.baeckerei-heidobler.de/bilder/aktionen/brezen_feld.jpg" alt="Brezen">
                                </div>

                                <div class="item img-responsive">
                                    <img src="http://volkskunde.files.wordpress.com/2011/11/festessen.jpg" alt="Brezen">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!--

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                        Collapsible Group 3</a>
                </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse">
                <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                    minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                    commodo consequat.</div>
            </div>
        </div>
    </div> 
</div> -->