
<div class="container">

    <div class="page-header">
        <h1>
            Mehr über...
        </h1>
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Feststand') ?></h3>
            </div>
            <div class="panel-body">
                <div class="col-lg-5">
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    </p>
                    <P>
                        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam 
                    </p>
                </div>

                <div class="col-lg-5 col-lg-offset-2">
                    <div id="Feststand" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                            <li data-target="#Feststand" data-slide-to="0" class="active"></li>
                            <li data-target="#Feststand" data-slide-to="1"></li>
                            <li data-target="#Feststand" data-slide-to="2"></li>
                            <li data-target="#Feststand" data-slide-to="3"></li>
                            <li data-target="#Feststand" data-slide-to="4"></li>
                        </ol>

                        <div class="carousel-inner" role="listbox">

                            <div class="item active">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive"  src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                        </div>

                        <a class="left carousel-control" href="#Feststand" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left control-color" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#Feststand" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right control-color" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div> 
        </div>
    </div>


    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Festwirtschaft') ?></h3>
            </div>
            <div class="panel-body">
                <div class="col-lg-5">
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam 
                    </p>
                </div>

                <div class="col-lg-5 col-lg-offset-2">
                    <div id="Festwirtschaft" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                            <li data-target="#Festwirtschaft" data-slide-to="0" class="active"></li>
                            <li data-target="#Festwirtschaft" data-slide-to="1"></li>
                            <li data-target="#Festwirtschaft" data-slide-to="2"></li>
                            <li data-target="#Festwirtschaft" data-slide-to="3"></li>
                            <li data-target="#Festwirtschaft" data-slide-to="4"></li>
                        </ol>

                        <div class="carousel-inner" role="listbox">

                            <div class="item active">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive"  src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                        </div>

                        <a class="left carousel-control" href="#Festwirtschaft" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left control-color" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#Festwirtschaft" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right control-color" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div> 
        </div>
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Gastrobetrieb') ?></h3>
            </div>
            <div class="panel-body">
                <div class="col-lg-5">
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam 
                    </p>
                </div>

                <div class="col-lg-5 col-lg-offset-2">
                    <div id="Gastrobetrieb" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                            <li data-target="#Gastrobetrieb" data-slide-to="0" class="active"></li>
                            <li data-target="#Gastrobetrieb" data-slide-to="1"></li>
                            <li data-target="#Gastrobetrieb" data-slide-to="2"></li>
                            <li data-target="#Gastrobetrieb" data-slide-to="3"></li>
                            <li data-target="#Gastrobetrieb" data-slide-to="4"></li>
                        </ol>

                        <div class="carousel-inner" role="listbox">

                            <div class="item active">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive"  src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                            <div class="item">
                                <img class="img-responsive" src="http://blogs.taz.de/arabesken/files/2012/05/testbild-sendepause.jpg" alt="...">
                                <div class="carousel-caption">
                                </div>
                            </div>

                        </div>

                        <a class="left carousel-control" href="#Gastrobetrieb" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left control-color" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#Gastrobetrieb" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right control-color" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>

