<div class="jumbotron text-center">
    <h1><?php echo sprintf($this->translate('Willkommen')) . ' !' ?></h1>
    <p><?php echo sprintf($this->translate('Hier ensteht das neue Teilnehmerportal der Badenfahrt 2016. Es bietet die Verwaltung sowie die Organisation des gesamten Festbetriebes')) ?> </p>
    <?php IF (!$this->zfcUserIdentity()): ?>
        <p><a class="btn btn-lg btn-info" href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('Registrieren'); ?></a>
            <a class="btn btn-lg btn-success" href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Login'); ?></a>
        </p>
    <?php endif; ?>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Festwirtschaft') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. ues coalesce, ilie. Lor separat existentie es un myth. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.')) ?></p>
                <p><a class="btn btn-info pull-right" href="/about"><?php echo $this->translate('Mehr über Festwirtschaft') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Feststand') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt.')) ?></p>
                <p><a class="btn btn-info pull-right" href="/about"><?php echo $this->translate('Mehr über Feststand') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Gastrobetrieb') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. ues coalesce, ilie. Lor separat existentie es un myth. Omnicos dire udeeretuices.')) ?></p>
                <p><a class="btn btn-info pull-right" href="/about"><?php echo $this->translate('Mehr über Gastrobetrieb') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
